backend:
  name: git-gateway
  branch: main

publish_mode: editorial_workflow

locale: 'pl'

show_preview_links: true

site_url: https://przemekmiros.pl
display_url: https://przemekmiros.pl
logo_url: https://przemekmiros.pl/assets/img/logo/logo.svg
  
media_folder: "src/assets/img/"
public_folder: "/assets/img/"

collections:
  - name: "posts"
    label: "Blog"
    folder: "src/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Tytuł", name: "title", widget: "string"}
      - {label: "Data", name: "date", widget: "datetime"}
      - {label: "Obrazek", name: "thumbnail", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "works"
    label: "Realizacje"
    folder: "src/realizacje"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "case"}
      - {label: "Tytuł", name: "title", widget: "string"}
      - {label: "Data", name: "date", widget: "datetime"}
      - {label: "Mockup", name: "thumbnail", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}
