backend:
  name: git-gateway
  branch: main
  
media_folder: "src/assets/img/"
public_folder: "/assets/img/"

collections:
  - name: "posts"
    label: "Blog"
    folder: "src/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "layouts/post"}
      - {label: "Tytuł", name: "title", widget: "string"}
      - {label: "Data", name: "date", widget: "datetime"}
      - {label: "Obrazek", name: "thumbnail", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "works"
    label: "Realizacje"
    folder: "src/realizacje"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "layouts/case"}
      - {label: "Tytuł", name: "title", widget: "string"}
      - {label: "Data", name: "date", widget: "datetime"}
      - {label: "Mockup", name: "thumbnail", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}
